### ISSUE TITLE
Google_IO_Exception error when using precache

### ISSUE THREAD

**Issue by JonKaric** [jrc9designstudio/statamic-google-analytics-v2#20]
I keep getting intermittent `Google_IO_Exception`  timeout errors.

Running latest Statamic & Google Analytics 

**Template fragment**
``` HTML
{{ collection:reviews filter="google_analytics" scope="post" sort="false" limit="20" period="30"}}
    {{ partial:listing }} 
{{ /collection:reviews }} 
```

**Stacktrace when loading the page. Pre-cache command isn't used**
```
production.ERROR: Google_IO_Exception in /Users/jonkaric/devsites/mysite/statamic/vendor/google/apiclient/src/Google/IO/Curl.php:126
Stack trace:
#0 /Users/jonkaric/devsites/mysite/statamic/vendor/google/apiclient/src/Google/IO/Abstract.php(136): Google_IO_Curl->executeRequest(Object(Google_Http_Request))
#1 /Users/jonkaric/devsites/mysite/statamic/vendor/google/apiclient/src/Google/Http/REST.php(60): Google_IO_Abstract->makeRequest(Object(Google_Http_Request))
#2 /Users/jonkaric/devsites/mysite/statamic/vendor/google/apiclient/src/Google/Task/Runner.php(174): Google_Http_REST::doExecute(Object(Google_Client), Object(Google_Http_Request))
#3 /Users/jonkaric/devsites/mysite/statamic/vendor/google/apiclient/src/Google/Http/REST.php(46): Google_Task_Runner->run()
#4 /Users/jonkaric/devsites/mysite/statamic/vendor/google/apiclient/src/Google/Client.php(593): Google_Http_REST::execute(Object(Google_Client), Object(Google_Http_Request))
#5 /Users/jonkaric/devsites/mysite/statamic/vendor/google/apiclient/src/Google/Service/Resource.php(240): Google_Client->execute(Object(Google_Http_Request))
#6 /Users/jonkaric/devsites/mysite/statamic/vendor/google/apiclient/src/Google/Service/Analytics.php(2052): Google_Service_Resource->call('get', Array, 'Google_Service_...')
#7 /Users/jonkaric/devsites/mysite/statamic/vendor/jrc9designstudio/statamic-laravel-analytics/src/AnalyticsClient.php(62): Google_Service_Analytics_DataGa_Resource->get('ga:my_ga_ID', '2005-01-01', '2020-04-24', 'ga:pageviews', Array)
#8 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(206): JRC9DS\Analytics\AnalyticsClient->JRC9DS\Analytics\{closure}()
#9 /Users/jonkaric/devsites/mysite/statamic/vendor/jrc9designstudio/statamic-laravel-analytics/src/AnalyticsClient.php(68): Illuminate\Cache\Repository->remember('JRC9DS.laravel-...', 1440, Object(Closure))
#10 /Users/jonkaric/devsites/mysite/statamic/vendor/jrc9designstudio/statamic-laravel-analytics/src/Analytics.php(166): JRC9DS\Analytics\AnalyticsClient->performQuery('my_ga_ID', Object(Carbon\Carbon), Object(Carbon\Carbon), 'ga:pageviews', Array)
#11 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(219): JRC9DS\Analytics\Analytics->performQuery(Object(JRC9DS\Analytics\Period), 'ga:pageviews', Array)
#12 /Users/jonkaric/devsites/mysite/site/addons/GoogleAnalytics/GoogleAnalyticsFilter.php(33): Illuminate\Support\Facades\Facade::__callStatic('performQuery', Array)
#13 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/Support/Collection.php(794): Statamic\Addons\GoogleAnalytics\GoogleAnalyticsFilter->Statamic\Addons\GoogleAnalytics\{closure}(Object(Statamic\Data\Entries\Entry), '62eeda0d-7135-4...')
#14 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/Support/Collection.php(819): Illuminate\Support\Collection->sortBy(Object(Closure), 0, true)
#15 /Users/jonkaric/devsites/mysite/site/addons/GoogleAnalytics/GoogleAnalyticsFilter.php(40): Illuminate\Support\Collection->sortByDesc(Object(Closure))
#16 /Users/jonkaric/devsites/mysite/statamic/bundles/Collection/CollectionTags.php(570): Statamic\Addons\GoogleAnalytics\GoogleAnalyticsFilter->filter(Object(Statamic\Data\Entries\EntryCollection))
#17 /Users/jonkaric/devsites/mysite/statamic/bundles/Collection/CollectionTags.php(544): Statamic\Addons\Collection\CollectionTags->customFilter('google_analytic...')
#18 /Users/jonkaric/devsites/mysite/statamic/bundles/Collection/CollectionTags.php(361): Statamic\Addons\Collection\CollectionTags->filterConditions()
#19 /Users/jonkaric/devsites/mysite/statamic/bundles/Collection/CollectionTags.php(106): Statamic\Addons\Collection\CollectionTags->filter()
#20 /Users/jonkaric/devsites/mysite/statamic/bundles/Collection/CollectionTags.php(82): Statamic\Addons\Collection\CollectionTags->collect(Object(Statamic\Data\Entries\EntryCollection))
#21 [internal function]: Statamic\Addons\Collection\CollectionTags->__call('reviews', Array)
#22 /Users/jonkaric/devsites/mysite/statamic/core/View/Antlers/Engine.php(163): call_user_func(Array)
#23 [internal function]: Statamic\View\Antlers\Engine::renderTag('collection', Array, '\n            {{...', Array)
#24 /Users/jonkaric/devsites/mysite/statamic/core/View/Antlers/Parser.php(513): call_user_func_array(Array, Array)
#25 /Users/jonkaric/devsites/mysite/statamic/core/View/Antlers/Parser.php(113): Statamic\View\Antlers\Parser->parseCallbackTags('<main class="ma...', Array, Array)
#26 /Users/jonkaric/devsites/mysite/statamic/core/View/Antlers/Template.php(32): Statamic\View\Antlers\Parser->parse('<main class="ma...', Array, Array, false)
#27 /Users/jonkaric/devsites/mysite/statamic/core/API/Parse.php(22): Statamic\View\Antlers\Template::parse('<main class="ma...', Array, Array)
#28 /Users/jonkaric/devsites/mysite/statamic/core/View/Antlers/Engine.php(70): Statamic\API\Parse::template('<main class="ma...', Array)
#29 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/View/View.php(147): Statamic\View\Antlers\Engine->get('/Users/jonkaric...', Array)
#30 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/View/View.php(118): Illuminate\View\View->getContents()
#31 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/View/View.php(83): Illuminate\View\View->renderContents()
#32 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/Http/Response.php(51): Illuminate\View\View->render()
#33 /Users/jonkaric/devsites/mysite/statamic/core/Http/Controllers/StatamicController.php(263): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#34 [internal function]: Statamic\Http\Controllers\StatamicController->index('/')
#35 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256): call_user_func_array(Array, Array)
#36 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction('index', Array)
#37 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(Statamic\Http\Controllers\StatamicController), Object(Illuminate\Routing\Route), 'index')
#38 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#39 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#40 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#42 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#43 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(68): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Statamic\Http\Controllers\StatamicController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'index')
#44 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Statamic\\Http\\C...', 'index')
#45 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#46 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(708): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#47 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#48 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#49 /Users/jonkaric/devsites/mysite/statamic/core/StaticCaching/Middleware/Cache.php(30): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 [internal function]: Statamic\StaticCaching\Middleware\Cache->handle(Object(Illuminate\Http\Request), Object(Closure))
#51 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#52 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#54 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(710): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#55 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(674): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#56 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#57 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#58 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#59 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#60 /Users/jonkaric/devsites/mysite/site/addons/SeoPro/Middleware/GenerateReport.php(13): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#61 [internal function]: Statamic\Addons\SeoPro\Middleware\GenerateReport->handle(Object(Illuminate\Http\Request), Object(Closure))
#62 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#63 /Users/jonkaric/devsites/mysite/statamic/vendor/barryvdh/laravel-debugbar/src/Middleware/Debugbar.php(51): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#64 [internal function]: Barryvdh\Debugbar\Middleware\Debugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#65 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#66 /Users/jonkaric/devsites/mysite/statamic/core/Http/Middleware/TransformsRequest.php(31): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#67 [internal function]: Statamic\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#68 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#69 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#70 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#71 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#72 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#73 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#74 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#75 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#76 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#77 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#78 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#79 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#80 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#81 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#82 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#83 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#84 /Users/jonkaric/devsites/mysite/statamic/core/StaticCaching/Middleware/Retrieve.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#85 [internal function]: Statamic\StaticCaching\Middleware\Retrieve->handle(Object(Illuminate\Http\Request), Object(Closure))
#86 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#87 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#88 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#89 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#90 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#91 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#92 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#93 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#94 /Users/jonkaric/devsites/mysite/index.php(155): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#95 /Users/jonkaric/.composer/vendor/laravel/valet/server.php(158): require('/Users/jonkaric...')
#96 {main} 
```
**Stacktrace (When using `php please googleanalytics:precache-hits --period=30` command**
```
[2020-04-25 12:30:52] production.ERROR: Google_IO_Exception: Operation timed out after 100003 milliseconds with 0 bytes received in /Users/jonkaric/devsites/mysite/statamic/vendor/google/apiclient/src/Google/IO/Curl.php:126
Stack trace:
#0 /Users/jonkaric/devsites/mysite/statamic/vendor/google/apiclient/src/Google/IO/Abstract.php(136): Google_IO_Curl->executeRequest(Object(Google_Http_Request))
#1 /Users/jonkaric/devsites/mysite/statamic/vendor/google/apiclient/src/Google/Http/REST.php(60): Google_IO_Abstract->makeRequest(Object(Google_Http_Request))
#2 /Users/jonkaric/devsites/mysite/statamic/vendor/google/apiclient/src/Google/Task/Runner.php(174): Google_Http_REST::doExecute(Object(Google_Client), Object(Google_Http_Request))
#3 /Users/jonkaric/devsites/mysite/statamic/vendor/google/apiclient/src/Google/Http/REST.php(46): Google_Task_Runner->run()
#4 /Users/jonkaric/devsites/mysite/statamic/vendor/google/apiclient/src/Google/Client.php(593): Google_Http_REST::execute(Object(Google_Client), Object(Google_Http_Request))
#5 /Users/jonkaric/devsites/mysite/statamic/vendor/google/apiclient/src/Google/Service/Resource.php(240): Google_Client->execute(Object(Google_Http_Request))
#6 /Users/jonkaric/devsites/mysite/statamic/vendor/google/apiclient/src/Google/Service/Analytics.php(2052): Google_Service_Resource->call('get', Array, 'Google_Service_...')
#7 /Users/jonkaric/devsites/mysite/statamic/vendor/jrc9designstudio/statamic-laravel-analytics/src/AnalyticsClient.php(62): Google_Service_Analytics_DataGa_Resource->get('ga:my_ga_ID', '2020-03-26', '2020-04-25', 'ga:pageviews', Array)
#8 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(206): JRC9DS\Analytics\AnalyticsClient->JRC9DS\Analytics\{closure}()
#9 /Users/jonkaric/devsites/mysite/statamic/vendor/jrc9designstudio/statamic-laravel-analytics/src/AnalyticsClient.php(68): Illuminate\Cache\Repository->remember('JRC9DS.laravel-...', 1440, Object(Closure))
#10 /Users/jonkaric/devsites/mysite/statamic/vendor/jrc9designstudio/statamic-laravel-analytics/src/Analytics.php(166): JRC9DS\Analytics\AnalyticsClient->performQuery('my_ga_ID', Object(Carbon\Carbon), Object(Carbon\Carbon), 'ga:pageviews', Array)
#11 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(219): JRC9DS\Analytics\Analytics->performQuery(Object(JRC9DS\Analytics\Period), 'ga:pageviews', Array)
#12 /Users/jonkaric/devsites/mysite/site/addons/GoogleAnalytics/Commands/PrecacheHitsCommand.php(76): Illuminate\Support\Facades\Facade::__callStatic('performQuery', Array)
#13 [internal function]: Statamic\Addons\GoogleAnalytics\Commands\PrecacheHitsCommand->handle()
#14 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#15 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/Console/Command.php(150): Illuminate\Container\Container->call(Array)
#16 /Users/jonkaric/devsites/mysite/statamic/vendor/symfony/console/Command/Command.php(238): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /Users/jonkaric/devsites/mysite/statamic/core/Console/EnhancesCommands.php(21): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /Users/jonkaric/devsites/mysite/statamic/vendor/symfony/console/Application.php(840): Statamic\Extend\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /Users/jonkaric/devsites/mysite/statamic/vendor/symfony/console/Application.php(190): Symfony\Component\Console\Application->doRunCommand(Object(Statamic\Addons\GoogleAnalytics\Commands\PrecacheHitsCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /Users/jonkaric/devsites/mysite/statamic/vendor/symfony/console/Application.php(114): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /Users/jonkaric/devsites/mysite/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /Users/jonkaric/devsites/mysite/please(48): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 {main}  
```

**Comment by jcohlmeyer** [comment]
The timeout is an issue. Although I can not reproduce it.

How many pages are in your collection?

I can catch the error so it does not break the front end of the website, but this does not really solve the issue of the timeout. I am not sure there is much I can do about that.
